site_name: shell class
site_author: 徐静
site_favicon: icon.ico
repo_url: https://github.com/DataXujing/shell-class/
pages:
  - 主页: index.md
  - shell教程: chapter1.md
  - bat批处理教程: chapter2.md
  - 参考文献: chapter3.md
  - 关于: about.md
theme: readthedocs
